### ISSUE TITLE
Allow rectangular pinholes for ISM

### ISSUE THREAD

**Issue by roflmaostc** [RainerHeintzmann/PointSpreadFunctions.jl#9]
If I understood it correctly, currently only circular pinholes are allowed?

But for a pixelated detector, it would make more sense to have square shaped apertures?

Best,
Felix

**Comment by RainerHeintzmann** [comment]
The confocal as well as the ISM psf calculation supports to define the pinhole type.
For ISM the default is a square-shaped pinhole. If you want a square-shaped pinhole for a normal confocal image, you can specify this as follows:
`pp_em = PSFParams(0.488, 1.4, 1.518; mode=ModeConfocal);
pp_ex = PSFParams(5, 1.4, 1.518);
h = psf((128,128), pp_em, pp_ex=pp_ex, pinhole=4.0, sampling=(0.04, 0.04), pinhole_ft=PointSpreadFunctions.box_pinhole_ft);
`
The excitation wavelength was set here to a really large value so that the emission PSF can essentially be seen by itself. As you see, you get a square-shaped PSF.
